#
# New Relic Infrastructure Perfmon On-Host Integration
#
integration_name: com.newrelic.perfmon
instances:
   - name: nri-perfmon-metrics
     command: metrics
     labels:
        environment: production
