#
# New Relic Infrastructure Perfmon Integration
#
name: com.newrelic.perfmon
description: Perfmon On-Host Integration
protocol_version: 1
os: windows
commands:
  metrics:
    command:
      - .\perfmon-infra-plugin\perfmon-infra-plugin.exe
    prefix: integration/perfmon-infra-plugin
    interval: 15
