#
# New Relic Infrastructure DirWatcher Integration
#
integration_name: com.newrelic.perfmon
instances:
   - name: perfmon-infra-plugin-metrics
     command: metrics
     labels:
        environment: production
